---

- name: Grafana Setup
  hosts: localhost
  gather_facts: false
  sudo: yes
  tasks:
    - name: Setting "SELINUX=disabled"
      shell: |
        echo "SELINUX=disabled" > /etc/sysconfig/selinux
        echo "SELINUXTYPE=targeted" >> /etc/sysconfig/selinux
    - name: Scanning Grafana service
      shell: |
        rpm -qa
      register: string

    - name: Creating Grafana Repository"
      shell: |
        echo "[grafana]" > /etc/yum.repos.d/grafana.repo
        echo "name=grafana" >> /etc/yum.repos.d/grafana.repo
        echo "baseurl=https://packages.grafana.com/oss/rpm" >> /etc/yum.repos.d/grafana.repo
        echo "repo_gpgcheck=1" >> /etc/yum.repos.d/grafana.repo
        echo "enabled=1" >> /etc/yum.repos.d/grafana.repo
        echo "gpgcheck=1" >> /etc/yum.repos.d/grafana.repo
        echo "gpgkey=https://packages.grafana.com/gpg.key" >> /etc/yum.repos.d/grafana.repo
        echo "sslverify=1" >> /etc/yum.repos.d/grafana.repo
        echo "sslcacert=/etc/pki/tls/certs/ca-bundle.crt" >> /etc/yum.repos.d/grafana.repo
      when: string.stdout.find('grafana') == -1 

    - name: Installing Grafana("username:admin" , "password:xflow@1234") and its Font Packages
      shell: |
        yum install -y grafana
        yum install -y fontconfig
        yum install -y freetype*
        yum install -y urw-fonts
        systemctl enable grafana-server
        systemctl restart grafana-server
        firewall-cmd --zone=public --add-port=3000/tcp --permanent
        firewall-cmd --reload
        grafana-cli admin reset-admin-password xflow@1234
      when: string.stdout.find('grafana') == -1
