---
- name: Setup node_exporter
  hosts: node_exporter

  tasks:
  - name: Creating node_exporter user group
    group: name="node_exporter"
    become: true


  - name: Creating node_exporter user
    user:
      name: node_exporter
      group: node_exporter
      system: yes
      shell: "/sbin/nologin"
      comment: "node_exporter nologin User"
      createhome: "no"
      state: present

  - name: Install node_exporter
    sudo : yes
    unarchive:
      src: "https://github.com/prometheus/node_exporter/releases/download/v0.16.0/node_exporter-0.16.0.linux-amd64.tar.gz"
      dest: /usr/share/
      remote_src: yes


  - name: Copy node_exporter file to bin
    copy:
      src: "/usr/share/node_exporter-0.16.0.linux-amd64/node_exporter"
      dest: "/usr/local/bin/"
      owner: node_exporter
      group: node_exporter
      remote_src: yes
      mode: 0755


  - name: Delete node_exporter folder
    file:
      path: '/usr/share/node_exporter-0.16.0.linux-amd64/'
      state: absent

  - name: create service file
    copy:
      content: |
               [Unit]
               Description=Prometheus exporter
               Documentation=https://github.com/prometheus/node_exporter
               Wants=network-online.target
               After=network-online.target
  
               [Service]
               Type=simple
               User=node_exporter
               Group=node_exporter
               ExecReload=/bin/kill -HUP $MAINPID
               ExecStart=/usr/local/bin/node_exporter \
                --collector.cpu \
                --collector.diskstats \
                --collector.filesystem \
                --collector.loadavg \
                --collector.meminfo \
                --collector.filefd \
                --collector.netdev \
                --collector.stat \
                --collector.netstat \
                --collector.systemd \
                --collector.uname \
                --collector.vmstat \
                --collector.time \
                --collector.mdadm \
                --collector.zfs \
                --collector.tcpstat \
                --collector.bonding \
                --collector.hwmon \
                --collector.arp \
                --web.listen-address=:9100 \
  
                SyslogIdentifier=node_exporter
                Restart=always
  
                [Install]
                WantedBy=multi-user.target
      dest: /etc/systemd/system/node_exporter.service

  - name: restart node_exporter
    service:
      name: node_exporter
      state: started
      enabled: yes
